# Generated by Django 3.2.8 on 2021-11-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.CharField(db_column='IdCliente', max_length=4, primary_key=True, serialize=False)),
                ('nombrecliente', models.CharField(db_column='NombreCliente', max_length=40)),
                ('direccioncliente', models.CharField(blank=True, db_column='DireccionCliente', max_length=50, null=True)),
                ('telefonocliente', models.CharField(blank=True, db_column='TelefonoCliente', max_length=10, null=True)),
                ('adeudos', models.FloatField(blank=True, db_column='Adeudos', null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompra', models.CharField(db_column='IdCompra', max_length=4, primary_key=True, serialize=False)),
                ('fechac', models.DateField(db_column='FechaC')),
                ('total', models.FloatField(db_column='Total')),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.CharField(db_column='IdProducto', max_length=4, primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='NombreProducto', max_length=40)),
                ('cantidadp', models.FloatField(db_column='CantidadP')),
                ('precio', models.FloatField(db_column='Precio')),
                ('detalles', models.CharField(blank=True, db_column='Detalles', max_length=60, null=True)),
                ('stock', models.FloatField(db_column='Stock')),
                ('fechacaducidad', models.DateField(db_column='FechaCaducidad')),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.CharField(db_column='IdProveedor', max_length=4, primary_key=True, serialize=False)),
                ('nomproveedor', models.CharField(db_column='NomProveedor', max_length=40)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('idruta', models.CharField(db_column='IdRuta', max_length=4, primary_key=True, serialize=False)),
                ('detalleruta', models.CharField(blank=True, db_column='DetalleRuta', max_length=100, null=True)),
            ],
            options={
                'db_table': 'rutas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('idvendedor', models.CharField(db_column='IdVendedor', max_length=4, primary_key=True, serialize=False)),
                ('nombrev', models.CharField(db_column='NombreV', max_length=45)),
            ],
            options={
                'db_table': 'vendedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.CharField(db_column='IdVenta', max_length=4, primary_key=True, serialize=False)),
                ('fechav', models.DateField(db_column='FechaV')),
                ('total', models.FloatField(db_column='Total')),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallescompras',
            fields=[
                ('idcompra', models.OneToOneField(db_column='IdCompra', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Cremeria_ToscanoApp.compras')),
                ('cantidadpc', models.FloatField(db_column='CantidadPC')),
                ('costop', models.FloatField(db_column='CostoP')),
                ('subtotalc', models.FloatField(db_column='SubTotalC')),
            ],
            options={
                'db_table': 'detallescompras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallesventas',
            fields=[
                ('idventa', models.OneToOneField(db_column='IdVenta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Cremeria_ToscanoApp.ventas')),
                ('cantidadpv', models.FloatField(db_column='CantidadPV')),
                ('costov', models.FloatField(db_column='CostoV')),
                ('subtotalv', models.FloatField(db_column='SubTotalV')),
            ],
            options={
                'db_table': 'detallesventas',
                'managed': False,
            },
        ),
    ]
